# Generated by Django 4.2.11 on 2024-04-14 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='admins',
        ),
        migrations.RemoveField(
            model_name='community',
            name='owner',
        ),
        migrations.AddField(
            model_name='community',
            name='admin',
            field=models.ManyToManyField(related_name='administered_communities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='moderator',
            field=models.ManyToManyField(related_name='moderated_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
