# Generated by Django 4.2.11 on 2024-04-20 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_defaultpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
