# Generated by Django 4.2.11 on 2024-04-20 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='community',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='application.community'),
        ),
    ]
