# Generated by Django 4.2.11 on 2024-05-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='isPrivate',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
