# Generated by Django 4.2.11 on 2024-05-10 12:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0016_community_isprivate'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='invited',
            field=models.ManyToManyField(related_name='invited_communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
