# Generated by Django 4.2.11 on 2024-05-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_post_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatefield',
            name='community',
        ),
    ]
